Milestone1
CollinsTatang/Newsweek-Clone pull request #1
Opened 2021-02-01 13:18 UTC by brytebee

## In order to master the use of Bootstrap as included in our lesson we have been given the tasks bellow:

### 1. Set up a new repository
### 2. Prepare the main HTML file
### 3. Install Bootstrap in your project
### 4. Prepare your project to work with 3 screen sizes: mobile, tablet, and desktop using the Bootstrap responsive grid classes
### 5. Create these sections of the website for the 3 screen sizes

2021-02-01 15:30 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello Bright Atsighi & Collins Tatang** 
Amazing job :tada: :tada: :tada: 
Now you are ready to continue with your next challenge :muscle: 

#### Feedback

- [ ] Don't forget to remove commented code from your index.html file
 
Keep going like this  :clap: :clap:
 
Oscar Andrés Russi Porras

2021-02-02 19:58 UTC, Spayco approved these changes
# Project Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone. but keep in mind **all these changes unless marked optional will be MANDATORY in the third milestone**.

- [ ] For Desktop size, `LATEST NEWS` should come after `MORE STORIES`
- [ ] For Desktop size, there's some extra `SPONSORED INSIGHT` on the bottom
- [ ] Turn the articles into links.


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-02 19:58 UTC, Spayco commented on style.css
> +  position: absolute;
- [ ] Use `d-block position-absolute` Bootstrap classes.

2021-02-02 19:58 UTC, Spayco commented on style.css
> +  position: absolute;
- [ ] Use `position-absolute` Bootstrap class.

2021-02-04 01:12 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
- The top navbar of your page does not look like the original. Please center the Newsweek logo. Also, the newsweek logo is supposed to be a link.

| Your version | Original version |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/106829584-0c9e8980-6652-11eb-9043-fa7adbfe61d3.png) | ![image](https://user-images.githubusercontent.com/2739245/106829653-2d66df00-6652-11eb-8e00-3e4387255504.png) |

- Also, please note that in the previous image, the VS badge in the 'THE DEBATE' section is misplaced. Please make sure it looks like the original.

- Your Sponsored Insight and Subscription sections are very different from the original. Please fix this:

| Your version | Original version |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/106829812-80d92d00-6652-11eb-80b5-4d298896b1dd.png) | ![image](https://user-images.githubusercontent.com/2739245/106829854-92bad000-6652-11eb-8d0b-2cdbc07a00a7.png) |

- Your In The Magazine section looks similar to the original, but notice how the first article has the same height as the remaining articles to it's right. Please fix this:

| Your version | Original version | 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/106829995-cb5aa980-6652-11eb-8f01-b841b3cb31a9.png) | ![image](https://user-images.githubusercontent.com/2739245/106830015-d8779880-6652-11eb-841c-f85a5436207e.png) |

- Your version is missing the U.S., World, Business, etc sections. Please add these before requesting for another review:

![image](https://user-images.githubusercontent.com/2739245/106830105-05c44680-6653-11eb-8ab2-8ac72d7e6db0.png)

- The Subscribe and Newsletter sections are supposed to have the same height. Also, the footer of the page is supposed to have the same width as the main column. Please fix this:

| Your version | Original version |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/106830208-386e3f00-6653-11eb-9426-5ff5e9fb2852.png) | ![image](https://user-images.githubusercontent.com/2739245/106830240-47ed8800-6653-11eb-9074-12fb1fb5a5b8.png) |

- Finally, on mobile and tablet views, your page is overflowing to the right. This makes it possible for the user to scroll to the right, which creates a gap on the right side of the page.

![image](https://user-images.githubusercontent.com/2739245/106830363-93079b00-6653-11eb-8c60-a919f2f2b680.png)


### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-04 19:03 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] the login button in the navbar would change to an icon on the mobile screen
- [ ] the subscribe and newsletter sections should have the same width on the desktop size

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-05 10:57 UTC, uryelah approved these changes
Hi **Bright Atsighi & Collins Tatang**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job implementing all the requests from the previous review!

You did a great job working out the responsiveness of the project and I specially like how you even used pseudo elements in your CSS!

Good luck with the next milestone! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---
    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-02-11 08:06 UTC, merged